### ISSUE TITLE
As a DevOps engineer, I want GitHub Actions integration so that migration checks run automatically on every PR

### ISSUE THREAD

**Issue by tommy2118** [tommy2118/rails-migration-guard#25]
## User Story

As a DevOps engineer using GitHub Actions, I want ready-to-use GitHub Actions workflow configurations so that I can add migration guard checks to our pull request process with minimal configuration.

### Acceptance Criteria

- [ ] Provide GitHub Action workflow example
- [ ] Action runs on pull_request events
- [ ] Checks for orphaned migrations
- [ ] Posts status check on PR
- [ ] Comments on PR with details if issues found
- [ ] Configurable via workflow inputs
- [ ] Works with matrix builds

### Technical Notes

```yaml
# .github/workflows/migration_guard.yml
name: Migration Guard Check
on:
  pull_request:
    paths:
      - 'db/migrate/**'
      - 'db/schema.rb'

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      - name: Check for orphaned migrations
        run: |
          bundle exec rails migration_guard:ci --strict
        env:
          RAILS_ENV: test
          DATABASE_URL: postgresql://localhost/test
```

### Related to Epic
- #10 (CI/CD Integration)

**Labels:** user-story, ci-cd
